[package]
name = "arbiter-documentation"
version = "0.0.0"
edition = "2021"

[dependencies]
arbiter-core = { path = "../arbiter-core" }
arbiter-bindings = { path = "../arbiter-bindings" }
tokio.workspace = true