[package]
name = "documentation"
version = "0.0.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
skeptic = "0.13.7"

[dev-dependencies]
skeptic = "0.13.7"
arbiter-core = { path = "../arbiter-core" }
arbiter-bindings = { path = "../arbiter-bindings" }
tokio.workspace = true