name: book

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      mdbook-path: ${{ steps.mdbook-path.outputs.path }}
      mdbook-template-path: ${{ steps.mdbook-template-path.outputs.path }}
      mdbook-linkcheck-path: ${{ steps.mdbook-linkcheck-path.outputs.path }}

    steps:
      - uses: actions/checkout@v3

      # Install Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      # Install mdbook
      - name: Install mdbook
        run: |
          mkdir mdbook
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        id: mdbook-path
        working-directory: ${{ github.workspace }}
        continue-on-error: false

      # Install mdbook-template
      - name: Install mdbook-template
        run: |
          mkdir mdbook-template
          curl -sSL https://github.com/sgoudham/mdbook-template/releases/latest/download/mdbook-template-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook-template
        id: mdbook-template-path
        working-directory: ${{ github.workspace }}
        continue-on-error: false

      # Install mdbook-linkcheck
      - name: Install mdbook-linkcheck
        run: |
          mkdir mdbook-linkcheck
          curl -sSL -o mdbook-linkcheck.zip https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/latest/download/mdbook-linkcheck.x86_64-unknown-linux-gnu.zip
          unzip mdbook-linkcheck.zip -d ./mdbook-linkcheck
          chmod +x mdbook-linkcheck/mdbook-linkcheck
        id: mdbook-linkcheck-path
        working-directory: ${{ github.workspace }}
        continue-on-error: false

  lint:
    needs: setup
    runs-on: ubuntu-latest
    name: lint

    steps:
      - uses: actions/checkout@v3

      - name: Run linkcheck
        run: mdbook-linkcheck --standalone
        env:
          PATH: ${{ needs.setup.outputs.mdbook-linkcheck-path }}:$PATH

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Build book
        run: mdbook build
        env:
          PATH: ${{ needs.setup.outputs.mdbook-path }}:$PATH

      - name: Build docs
        run: RUSTDOCFLAGS="--enable-index-page -Zunstable-options" cargo +nightly doc --all --no-deps
