name: book

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      mdbook-path: ${{ steps.mdbook-path.outputs.path }}
      mdbook-template-path: ${{ steps.mdbook-template-path.outputs.path }}
      mdbook-linkcheck-path: ${{ steps.mdbook-linkcheck-path.outputs.path }}

    steps:
      - uses: actions/checkout@v3

      # Install Rust
      - name: install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      # Install mdbook
      - name: install mdbook
        run: cargo install mdbook --vers "^0.4.35"
        continue-on-error: false

      # Install mdbook-linkcheck
      - name: install mdbook-linkcheck
        run: cargo install mdbook-linkcheck
        continue-on-error: false

      # Install mdbook-keeper
      - name: install mdbook-keeper
        run: cargo install mdbook-keeper --version "^0.4.0"
        continue-on-error: false

  lint:
    needs: setup
    runs-on: ubuntu-latest
    name: lint

    steps:
      - uses: actions/checkout@v3

      - name: run linkcheck
        run: mdbook-linkcheck --standalone

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: build book
        run: mdbook build
