name: book

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install Rust
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      # Install mdbook
      - name: Install mdbook
        run: cargo install mdbook --vers "^0.4.35"

      # Install mdbook-keeper
      - name: Install mdbook-keeper
        run: cargo install mdbook-keeper --version "^0.4.0"

      # Install mdbook-linkcheck
      - name: Install mdbook-linkcheck
        run: cargo install mdbook-linkcheck

      # Install mdbook-katex
      - name: Install mdbook-katex
        run: cargo install mdbook-katex

      # Build book
      - name: Build book
        run: |
          set -e
          mdbook build
